site:
  baseUrl: ${WIKI_BASE_URL}
  links:
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/AVN_HEP_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/AVN_REC_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/AVN_RFS_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/AVN_SFW_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/AVN_STR_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/HEP_RFS_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/HEP_SFW_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/HEP_STR_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/PSS_HEP_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/PSS_RFS_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/PSS_STR_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/REC_SFW_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/REC_STR_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/RFS_SFW_ICD
    - en/rocketry/teams/HERMES/Systems_Engineering/ICD_Export/RFS_STR_ICD

  cookies:
    - key: jwt
      value: ${WIKIJS_JWT_TOKEN}
browser:
  headless: ${CHROMIUM_HEADLESS_MODE:-true}
  inject:
    css:
      - content: |
          nav.v-navigation-drawer,header.v-sheet,footer.v-footer{display: none;}
          main.v-main{padding: 0 !important;}
concurrency: 1
output:
  filename: ICD
